# Generated by Django 5.0.3 on 2024-04-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_alter_consumer_id_alter_contact_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.TextField(null=True),
        ),
    ]
